services:
  postgres:
    image: postgres:17
    container_name: postgres_internship
    environment:
      POSTGRES_DB: internship
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: