spring:
  application:
    name: internship
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/internship
    username: postgres
    password: password123
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/changelog-master.yml
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 25MB
      max-request-size: 30MB
      resolve-lazily: true

jwt:
  lifetime: 1h
  secret: 7cc5f72d8500f4f68addccaa218998a2b855134bc0a04bdd13c06cb467c5293a

logging:
  level:
    org.springframework.security: DEBUG
    io.minio: WARN


minio:
  endpoint: http://77.110.109.183:9000
  access-key: StoTE3XvrvY5dmHnjmtT
  secret-key: DpItdtwdQC7WqeyHwDyHm8BHFWLc7t5Xa3f2TsGl
  bucket-name: files
  connect-timeout: 5000
  write-timeout: 15000
  read-timeout: 15000

export:
  student-batch-size: 100