spring:
  application:
    name: internship
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/internship
    username: postgres
    password: postgres
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/changelog-master.yml
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
jwt:
  lifetime: 1h
  secret: 7cc5f72d8500f4f68addccaa218998a2b855134bc0a04bdd13c06cb467c5293a